### ISSUE TITLE
Port the UT_LIST changes from InnoDB 8.x

### ISSUE THREAD

**Issue by subains** [sunbains/embedded-innodb#16]
Makes iterating over the UT_LIST similar to other STL containers.

**Comment by RahulKushwaha** [comment]
Porting the current implementation should be fine right? https://github.com/mysql/mysql-server/blob/trunk/storage/innobase/include/ut0lst.h

Tried porting the above file, only `sync0sync.h` is giving trouble. Otherwise things look fine. I will try fixing it.

**Comment by RahulKushwaha** [comment]
Draft PR with changes: https://github.com/RahulKushwaha/embedded-innodb/pull/2/files#
Build is successful, but failing tests. I think I mis-wired some of the variables. 

Assertion in file `trx0trx.cc` is failing: `ut_ad(UT_LIST_GET_LEN(trx->trx_locks) == 0);`
Seems like when we try to release the locks via `lock_release_off_kernel` it does not work.  `lock_table_dequeue` is not able to iterate on all the locks. 
I will keep working on this. 

Secondly, do you mind checking-in the clang-format file?

**Comment by sunbains** [comment]
Thanks. I've transferred the ownership to my personal account. In case you have problems rebasing.

**Comment by sunbains** [comment]
I merge your code with main with  some fixes and created a branch ut_list. You can rebase off that.

**Comment by sunbains** [comment]
I fixed the bug that was causing ib_ddl to fail. I think it's in the ut0lst.h code. Not in your change.

**Comment by RahulKushwaha** [comment]
Working on the ut_list branch. tests crashing in method `pars_resolve_exp_variables_and_types`. it is not able to resolve the sym. Problem with list i guess. I will dig more.
